apply from: file("buildSrc/common-settings.gradle")

rootProject.name = 'gw-utils'
include 'core:codec', 'core:date', 'core:enums', 'core:exceptions', 'core:jackson', 'core:lang', 'core:reflection', 'core:tree', 'core:uuid'
include 'data:commons', 'data:spring'
include 'i18n'
include 'javafx:base', 'javafx:controls', 'javafx:spring'
include 'web:converter', 'web:core', 'web:json'
