dependencies {
    api(libs.slf4j.api) {
        exclude group: 'org.slf4j', module: 'logback'
    }
    api(libs.spring.context)
    compileOnly(libs.lombok)
    annotationProcessor(libs.lombok)
    testImplementation(libs.junit.jupiter.engine)
    testImplementation(libs.junit.platform.launcher)
    testImplementation(libs.mockito.core)
}
