def os = org.gradle.internal.os.OperatingSystem.current()
def arch = System.getProperty('os.arch')
def javafxPlatform = os.isWindows() ? 'win' : os.isMacOsX() ? (arch == 'aarch64' ? 'mac-aarch64' : 'mac') : 'linux'

dependencies {
    implementation(project(':core:exceptions'))
    implementation(project(':i18n'))
    implementation(project(':javafx:base'))
    implementation(libs.spring.beans)
    implementation(libs.spring.context)
    implementation(libs.spring.core)
    implementation(libs.spring.boot.autoconfigure)
    implementation "org.openjfx:javafx-base:${libs.versions.openjfx.get() as String}:${javafxPlatform}"
    implementation "org.openjfx:javafx-controls:${libs.versions.openjfx.get() as String}:${javafxPlatform}"
    implementation "org.openjfx:javafx-fxml:${libs.versions.openjfx.get() as String}:${javafxPlatform}"
    implementation "org.openjfx:javafx-graphics:${libs.versions.openjfx.get() as String}:${javafxPlatform}"
    api(libs.slf4j.api) {
        exclude group: 'org.slf4j', module: 'logback'
    }
    compileOnly(libs.jspecify)
    compileOnly(libs.lombok)
    annotationProcessor(libs.lombok)

    testImplementation(libs.junit.jupiter.engine)
    testImplementation(libs.junit.platform.launcher)
    testImplementation(libs.assertj.core)
    testImplementation(libs.mockito.core)
    testImplementation('org.testfx:testfx-core:4.0.18')
    testImplementation('org.testfx:testfx-junit5:4.0.18')
    testImplementation('org.testfx:openjfx-monocle:jdk-11+26')
    testImplementation(libs.spring.boot.starter)
    testImplementation(libs.spring.boot.starter.test)
    testRuntimeOnly("org.openjfx:javafx-graphics:${libs.versions.openjfx.get() as String}:${javafxPlatform}")
}
