plugins {
    id 'java'
    id 'java-gradle-plugin'
}

apply from: file("common-resolution-strategy.gradle")

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
    withSourcesJar()
    withJavadocJar()
}

def rootProps = new Properties()
file("${rootDir}/../gradle.properties").withInputStream { rootProps.load(it) }

def versionMap = rootProps.collectEntries { key, value ->
    String propKey = key.toString()
    String alias = propKey.endsWith('.version') ? propKey[0..-9] : propKey
    [(alias): value.toString()]
}
VersionCatalogsExtension catalogs = rootProject.extensions.findByType(VersionCatalogsExtension)
VersionCatalog libs = catalogs?.find("libs")?.orElse(null)

configurations {
    configureEach { config ->
        rootProject.ext.applyCommonResolutionStrategy(config, libs, versionMap)
    }
}

dependencies {
    implementation gradleApi()

    implementation "com.gradleup.shadow:com.gradleup.shadow.gradle.plugin:${rootProps['shadow.plugin.version']}"
    implementation "com.fasterxml.jackson.core:jackson-databind:${rootProps['jackson2.core.version']}"
}
